from arvore_t2 import Arvore

def main():

    persona = Arvore("FATEC Adamantina")
    persona.raiz.inserir_filho("Ciência de Dados")
    persona.inserir_nodo("Ciência de Dados", "Primeiro Módulo")
    persona.inserir_nodo("Primerio Módulo", "Disciplina")
    persona.inserir_nodo("Discilpina", "Algoritmos e Introdução à Computação")
    persona.inserir_nodo("Algoritmos e Introdução à Computação", "Prof.1:")
    persona.inserir_nodo("Prof.1:", "Eliane Vendramini")
    persona.inserir_nodo("Disciplina", "Gestão Ágil de Projetos")
    persona.inserir_nodo("Gestão Ágil de Projetos", "Prof.2:")
    persona.inserir_nodo("Prof.2:", "Eliane Vendramini")
    persona.inserir_nodo("Disciplina", "Matemática Básica")
    persona.inserir_nodo("Matemática Básica", "Prof.3:")
    persona.inserir_nodo("Prof.3:", "Renata Imada")
    persona.inserir_nodo("Disciplina", "Princípios de Ciência de Dados")
    persona.inserir_nodo("Princípios de Ciência de Dados", "Prof.4:")
    persona.inserir_nodo("Prof.4:", "Rafael Christofano")
    persona.inserir_nodo("Disciplina", "Economia da Informação, Inovação e Negócios Disruptivos")
    persona.inserir_nodo("Economia da Informação, Inovação e Negócios Disruptivos", "Prof.5:")
    persona.inserir_nodo("Prof.5:", "Luciana Marcondes")
    persona.inserir_nodo("Disciplina", "Produção de Textos Acadêmicos-Científicos I")
    persona.inserir_nodo("Produção de Textos Acadêmicos-Científicos I", "Prof.6:")
    persona.inserir_nodo("Prof.6:", "William Pereira")
    persona.inserir_nodo("Disciplina", "Inglês I")
    persona.inserir_nodo("Inglês I", "Prof.7:")
    persona.inserir_nodo("Prof.7:", "Renata Belchior")
    persona.inserir_nodo("Disciplina", "Metodologia da Pesquisa Científico-Tecnológica")
    persona.inserir_nodo("Metodologia da Pesquisa Científico-Tecnológica", "Prof.8:")
    persona.inserir_nodo("Prof.8:", "Alessandra")
    persona.inserir_nodo("Ciência de Dados", "Segundo Módulo")
    persona.inserir_nodo("Segundo Módulo", "Disciplina")
    persona.inserir_nodo("Disciplina","Estrutura de Dados")
    persona.inserir_nodo("Estrutura de Dados", "Prof.9:")
    persona.inserir_nodo("Prof.9:", "Eliane Vendramini")
    persona.inserir_nodo("Disciplina", "Estatística Descritiva")
    persona.inserir_nodo("Estatística Descritiva", "Prof.10:")
    persona.inserir_nodo("Prof.10:", "Thays")
    persona.inserir_nodo("Disciplina", "Álgebra Linear")
    persona.inserir_nodo("Álgebra Linear", "Prof.11:")
    persona.inserir_nodo("Prof.11:", "Renata Imada")
    persona.inserir_nodo("Disciplina", "Projeto Integrador")
    persona.inserir_nodo("Projeto Integrador", "Prof.12:")
    persona.inserir_nodo("Prof.12:", "Rafael Christofano")
    persona.inserir_nodo("Disciplina", "Ciência de Dados e Marketing Digital")
    persona.inserir_nodo("Ciência de Dados e Marketing Digital", "Prof.13:")
    persona.inserir_nodo("Prof.13:", "Rafael Christofano")
    persona.inserir_nodo("Disciplina", "Produção de Textos Acadêmicos-Científicos II")
    persona.inserir_nodo("Produção de Textos Acadêmicos-Científicos II", "Prof.14:")
    persona.inserir_nodo("Prof.14:", "Jaqueline")
    persona.inserir_nodo("Disciplina", "Inglês II")
    persona.inserir_nodo("Inglês II", "Prof.15:")
    persona.inserir_nodo("Prof.15:", "Renata Belchior")
    persona.inserir_nodo("Ciência de Dados", "Terceiro Módulo")
    persona.inserir_nodo("Ciência de Dados", "Quarto Módulo")
    persona.inserir_nodo("Ciência de Dados", "Quinto Módulo")
    persona.inserir_nodo("Ciência de Dados", "Sexto Módulo")
    persona.raiz.inserir_filho("Gestão Comercial")
    persona.inserir_nodo("Gestão Comercial", "Primeiro Módulo")
    persona.inserir_nodo("Gestão Comercial", "Segundo Módulo")
    persona.inserir_nodo("Gestão Comercial", "Terceiro Módulo")
    persona.inserir_nodo("Gestão Comercial", "Quarto Módulo")
    persona.inserir_nodo("Gestão Comercial", "Quinto Módulo")
    persona.inserir_nodo("Gestão Comercial", "Sexto Módulo")
    persona.inserir_nodo("Algoritmos e Introdução à Computação", "Estudante")
    persona.inserir_nodo("Estudante", "Eliz")
    persona.inserir_nodo("Algoritmos e Introdução à Computação", "Estudante")
    persona.inserir_nodo("Estudante", "Flavio")
    persona.inserir_nodo("Gestão Ágil de Projetos", "Estudante")
    persona.inserir_nodo("Estudante", "Eliz")
    persona.inserir_nodo("Gestão Ágil de Projetos", "Estudante")
    persona.inserir_nodo("Estudante", "Flavio")
    persona.inserir_nodo("Matemática Básica", "Estudante")
    persona.inserir_nodo("Estudante", "Eliz")
    persona.inserir_nodo("Matemática Básica", "Estudante")
    persona.inserir_nodo("Estudante", "Flavio")
    persona.inserir_nodo("Princípios de Ciência de Dados", "Estudante")
    persona.inserir_nodo("Estudante", "Eliz")
    persona.inserir_nodo("Princípios de Ciência de Dados", "Estudante")
    persona.inserir_nodo("Estudante", "Flavio")
    persona.inserir_nodo("Economia da Informação, Inovação e Negócios Disruptivos", "Estudante")
    persona.inserir_nodo("Estudante", "Eliz")
    persona.inserir_nodo("Economia da Informação, Inovação e Negócios Disruptivos", "Estudante")
    persona.inserir_nodo("Estudante", "Flavio")
    persona.inserir_nodo("Produção de Textos Acadêmicos-Científicos I", "Estudante")
    persona.inserir_nodo("Estudante", "Eliz")
    persona.inserir_nodo("Produção de Textos Acadêmicos-Científicos I", "Estudante")
    persona.inserir_nodo("Estudante", "Flavio")
    persona.inserir_nodo("Inglês I", "Estudante")
    persona.inserir_nodo("Estudante", "Eliz")
    persona.inserir_nodo("Inglês I", "Estudante")
    persona.inserir_nodo("Estudante", "Flavio")
    persona.inserir_nodo("Metodologia da Pesquisa Científico-Tecnológica", "Estudante")
    persona.inserir_nodo("Estudante", "Eliz")
    persona.inserir_nodo("Metodologia da Pesquisa Científico-Tecnológica", "Estudante")
    persona.inserir_nodo("Estudante", "Flavio")
    persona.inserir_nodo("Estrutura de Dados", "Estudante")
    persona.inserir_nodo("Estudante", "Eliz")
    persona.inserir_nodo("Estrutura de Dados", "Estudante")
    persona.inserir_nodo("Estudante", "Flavio")
    persona.inserir_nodo("Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini", "Flavio")
    persona.inserir_nodo("Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini", "Leticia")
    persona.inserir_nodo("Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini", "Gabriel")
    persona.inserir_nodo("Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini", "Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Estatística Descritiva - Prof.: Thays", "Eliz")
    persona.inserir_nodo("Disciplina: Estatística Descritiva - Prof.: Thays", "Flavio")
    persona.inserir_nodo("Disciplina: Estatística Descritiva - Prof.: Thays", "Leticia")
    persona.inserir_nodo("Disciplina: Estatística Descritiva - Prof.: Thays", "Gabriel")
    persona.inserir_nodo("Disciplina: Estatística Descritiva - Prof.: Thays", "Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Álgebra Linear - Prof.: Renata Imada", "Eliz")
    persona.inserir_nodo("Disciplina: Álgebra Linear - Prof.: Renata Imada", "Flavio")
    persona.inserir_nodo("Disciplina: Álgebra Linear - Prof.: Renata Imada", "Leticia")
    persona.inserir_nodo("Disciplina: Álgebra Linear - Prof.: Renata Imada", "Gabriel")
    persona.inserir_nodo("Disciplina: Álgebra Linear - Prof.: Renata Imada", "Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Projeto Integrador - Prof.: Rafael Christofano", "Eliz")
    persona.inserir_nodo("Disciplina: Projeto Integrador - Prof.: Rafael Christofano", "Flavio")
    persona.inserir_nodo("Disciplina: Projeto Integrador - Prof.: Rafael Christofano", "Leticia")
    persona.inserir_nodo("Disciplina: Projeto Integrador - Prof.: Rafael Christofano", "Gabriel")
    persona.inserir_nodo("Disciplina: Projeto Integrador - Prof.: Rafael Christofano", "Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano", "Eliz")
    persona.inserir_nodo("Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano", "Flavio")
    persona.inserir_nodo("Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano", "Leticia")
    persona.inserir_nodo("Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano", "Gabriel")
    persona.inserir_nodo("Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano", "Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline", "Eliz")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline", "Flavio")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline", "Leticia")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline", "Gabriel")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline", "Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Inglês II - Prof.: Renata Belchior", "Eliz")
    persona.inserir_nodo("Disciplina: Inglês II - Prof.: Renata Belchior", "Flavio")
    persona.inserir_nodo("Disciplina: Inglês II - Prof.: Renata Belchior", "Leticia")
    persona.inserir_nodo("Disciplina: Inglês II - Prof.: Renata Belchior", "Gabriel")
    persona.inserir_nodo("Disciplina: Inglês II - Prof.: Renata Belchior", "Luiz Gabriel")
    persona.imprimir()

    encontrado = persona.buscar(input("\nDigite um nome para confirmar se está na estrutura: "))
    print("\nEncontrado - {}".format(encontrado))

main()