from arvore_t2 import Arvore

def main():

    persona = Arvore("FATEC Adamantina")
    persona.raiz.inserir_filho("Ciência de Dados")
    persona.inserir_nodo("Ciência de Dados", "Primeiro Módulo")
    persona.inserir_nodo("Primeiro Módulo", "Algoritmos e Introdução à Computação")
    persona.inserir_nodo("Primeiro Módulo", "Gestão Ágil de Projetos")
    persona.inserir_nodo("Primeiro Módulo", "Matemática Básica")
    persona.inserir_nodo("Primeiro Módulo", "Princípios de Ciência de Dados")
    persona.inserir_nodo("Primeiro Módulo", "Economia da Informação, Inovação e Negócios Disruptivos")
    persona.inserir_nodo("Primeiro Módulo", "Produção de Textos Acadêmicos-Científicos I")
    persona.inserir_nodo("Primeiro Módulo", "Inglês I")
    persona.inserir_nodo("Primeiro Módulo", "Metodologia da Pesquisa Científico-Tecnológica")
    persona.inserir_nodo("Ciência de Dados", "Segundo Módulo")
    persona.inserir_nodo("Segundo Módulo", "Estrutura de Dados")
    persona.inserir_nodo("Segundo Módulo", "Estatística Descritiva")
    persona.inserir_nodo("Segundo Módulo", "Álgebra Linear")
    persona.inserir_nodo("Segundo Módulo", "Projeto Integrador")
    persona.inserir_nodo("Segundo Módulo", "Ciência de Dados e Marketing Digital")
    persona.inserir_nodo("Segundo Módulo", "Produção de Textos Acadêmicos-Científicos II")
    persona.inserir_nodo("Segundo Módulo", "Inglês II")
    persona.inserir_nodo("Ciência de Dados", "Terceiro Módulo")
    persona.inserir_nodo("Ciência de Dados", "Quarto Módulo")
    persona.inserir_nodo("Ciência de Dados", "Quinto Módulo")
    persona.inserir_nodo("Ciência de Dados", "Sexto Módulo")
    persona.raiz.inserir_filho("Gestão Comercial")
    persona.inserir_nodo("Gestão Comercial", "Primeiro Módulo")
    persona.inserir_nodo("Gestão Comercial", "Segundo Módulo")
    persona.inserir_nodo("Gestão Comercial", "Terceiro Módulo")
    persona.inserir_nodo("Gestão Comercial", "Quarto Módulo")
    persona.inserir_nodo("Gestão Comercial", "Quinto Módulo")
    persona.inserir_nodo("Gestão Comercial", "Sexto Módulo")
    persona.inserir_nodo("Algoritmos e Introdução à Computação", "Eliane Vendramini")
    persona.inserir_nodo("Algoritmos e Introdução à Computação", "Eliz")
    persona.inserir_nodo("Algoritmos e Introdução à Computação", "Flavio")
    persona.inserir_nodo("Gestão Ágil de Projetos", "Eliane Vendramini")
    persona.inserir_nodo("Gestão Ágil de Projetos", "Eliz")
    persona.inserir_nodo("Gestão Ágil de Projetos", "Flavio")
    persona.inserir_nodo("Matemática Básica", "Renata Imada")
    persona.inserir_nodo("Princípios de Ciência de Dados", "Rafael Christofano")
    persona.inserir_nodo("Princípios de Ciência de Dados", "Eliz")
    persona.inserir_nodo("Princípios de Ciência de Dados", "Flavio")
    persona.inserir_nodo("Economia da Informação, Inovação e Negócios Disruptivos", "Luciana Marcondes")
    persona.inserir_nodo("Economia da Informação, Inovação e Negócios Disruptivos", "Eliz")
    persona.inserir_nodo("Economia da Informação, Inovação e Negócios Disruptivos", "Flavio")
    persona.inserir_nodo("Produção de Textos Acadêmicos-Científicos I", "William Pereira")
    persona.inserir_nodo("Produção de Textos Acadêmicos-Científicos I", "Eliz")
    persona.inserir_nodo("Metodologia da Pesquisa Científico-Tecnológica", "Alessandra")
    persona.inserir_nodo("Inglês I", "Renata Belchior")
    persona.inserir_nodo("Estrutura de Dados", "Eliane Vendramini")
    persona.inserir_nodo("Estrutura de Dados", "Eliz")
    persona.inserir_nodo("Estrutura de Dados", "Flavio")
    persona.inserir_nodo("Estrutura de Dados", "Leticia")
    persona.inserir_nodo("Estrutura de Dados", "Gabriel")
    persona.inserir_nodo("Estrutura de Dados", "Luiz Gabriel")
    persona.inserir_nodo("Estatística Descritiva", "Thays")
    persona.inserir_nodo("Estatística Descritiva", "Leticia")
    persona.inserir_nodo("Estatística Descritiva", "Gabriel")
    persona.inserir_nodo("Estatística Descritiva", "Luiz Gabriel")
    persona.inserir_nodo("Álgebra Linear", "Renata Imada")
    persona.inserir_nodo("Álgebra Linear", "Eliz")
    persona.inserir_nodo("Álgebra Linear", "Flavio")
    persona.inserir_nodo("Álgebra Linear", "Leticia")
    persona.inserir_nodo("Álgebra Linear", "Gabriel")
    persona.inserir_nodo("Álgebra Linear", "Luiz Gabriel")
    persona.inserir_nodo("Projeto Integrador", "Rafael Christofano")
    persona.inserir_nodo("Projeto Integrador", "Leticia")
    persona.inserir_nodo("Projeto Integrador", "Gabriel")
    persona.inserir_nodo("Projeto Integrador", "Luiz Gabriel")
    persona.inserir_nodo("Ciência de Dados e Marketing Digital", "Rafael Christofano")
    persona.inserir_nodo("Ciência de Dados e Marketing Digital", "Leticia")
    persona.inserir_nodo("Ciência de Dados e Marketing Digital", "Gabriel")
    persona.inserir_nodo("Ciência de Dados e Marketing Digital", "Luiz Gabriel")
    persona.inserir_nodo("Produção de Textos Acadêmicos-Científicos II", "Jaqueline")
    persona.inserir_nodo("Produção de Textos Acadêmicos-Científicos II", "Leticia")
    persona.inserir_nodo("Produção de Textos Acadêmicos-Científicos II", "Gabriel")
    persona.inserir_nodo("Produção de Textos Acadêmicos-Científicos II", "Luiz Gabriel")
    persona.inserir_nodo("Inglês II", "Renata Belchior")
    persona.inserir_nodo("Inglês II", "Leticia")
    persona.inserir_nodo("Inglês II", "Gabriel")
    persona.inserir_nodo("Inglês II", "Luiz Gabriel")
    persona.imprimir()

    encontrado = persona.buscar(input("\nDigite um nome para encontrar quais disciplinas estão relacionadas na estrutura: "))
    print("\nEncontrado - {}".format(encontrado))

main()