from arvore_t2 import Arvore

def main():

    persona = Arvore("FATEC Adamantina")
    persona.raiz.inserir_filho("Ciência de Dados")
    persona.inserir_nodo("Ciência de Dados", "Primeiro Módulo")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Algoritmos e Introdução à Computação - Prof.: Eliane Vendramini")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Gestão Ágil de Projetos - Prof.: Eliane Vendramini")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Matemática Básica - Prof.: Renata Imada")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Princípios de Ciência de Dados - Prof.: Rafael Christofano")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Economia da Informação, Inovação e Negócios Disruptivos - Prof.: Luciana Marcondes")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Produção de Textos Acadêmicos-Científicos I - Prof.: William Pereira")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Inglês I - Prof.: Renata Belchior")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Metodologia da Pesquisa Científico-Tecnológica - Prof.: Alessandra")
    persona.inserir_nodo("Ciência de Dados", "Segundo Módulo")
    persona.inserir_nodo("Segundo Módulo", "Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini")
    persona.inserir_nodo("Segundo Módulo", "Disciplina: Estatística Descritiva - Prof.: Thays")
    persona.inserir_nodo("Segundo Módulo", "Disciplina: Álgebra Linear - Prof.: Renata Imada")
    persona.inserir_nodo("Segundo Módulo", "Disciplina: Projeto Integrador - Prof.: Rafael Christofano")
    persona.inserir_nodo("Segundo Módulo", "Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano")
    persona.inserir_nodo("Segundo Módulo", "Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline")
    persona.inserir_nodo("Segundo Módulo", "Disciplina: Inglês II - Prof.: Renata Belchior")
    persona.inserir_nodo("Ciência de Dados", "Terceiro Módulo")
    persona.inserir_nodo("Ciência de Dados", "Quarto Módulo")
    persona.inserir_nodo("Ciência de Dados", "Quinto Módulo")
    persona.inserir_nodo("Ciência de Dados", "Sexto Módulo")
    persona.raiz.inserir_filho("Gestão Comercial")
    persona.inserir_nodo("Gestão Comercial", "Primeiro Módulo")
    persona.inserir_nodo("Gestão Comercial", "Segundo Módulo")
    persona.inserir_nodo("Gestão Comercial", "Terceiro Módulo")
    persona.inserir_nodo("Gestão Comercial", "Quarto Módulo")
    persona.inserir_nodo("Gestão Comercial", "Quinto Módulo")
    persona.inserir_nodo("Gestão Comercial", "Sexto Módulo")
    persona.inserir_nodo("Disciplina: Algoritmos e Introdução à Computação - Prof.: Eliane Vendramini", "Estudante: Eliz")
    persona.inserir_nodo("Disciplina: Algoritmos e Introdução à Computação - Prof.: Eliane Vendramini", "Estudante: Flávio")
    persona.inserir_nodo("Disciplina: Gestão Ágil de Projetos - Prof.: Eliane Vendramini", "Estudante: Eliz")
    persona.inserir_nodo("Disciplina: Gestão Ágil de Projetos - Prof.: Eliane Vendramini", "Estudante: Flávio")
    persona.inserir_nodo("Disciplina: Matemática Básica - Prof.: Renata Imada", "Estudante: Eliz")
    persona.inserir_nodo("Disciplina: Matemática Básica - Prof.: Renata Imada", "Estudante: Flávio")
    persona.inserir_nodo("Disciplina: Princípios de Ciência de Dados - Prof.: Rafael Christofano", "Estudante: Eliz")
    persona.inserir_nodo("Disciplina: Princípios de Ciência de Dados - Prof.: Rafael Christofano", "Estudante: Flávio")
    persona.inserir_nodo("Disciplina: Economia da Informação, Inovação e Negócios Disruptivos - Prof.: Luciana Marcondes", "Estudante: Eliz")
    persona.inserir_nodo("Disciplina: Economia da Informação, Inovação e Negócios Disruptivos - Prof.: Luciana Marcondes", "Estudante: Flávio")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos I - Prof.: William Pereira", "Estudante: Eliz")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos I - Prof.: William Pereira", "Estudante: Flávio")
    persona.inserir_nodo("Disciplina: Inglês I - Prof.: Renata Belchior", "Estudante: Eliz")
    persona.inserir_nodo("Disciplina: Inglês I - Prof.: Renata Belchior", "Estudante: Flávio")
    persona.inserir_nodo("Disciplina: Metodologia da Pesquisa Científico-Tecnológica - Prof.: Alessandra", "Estudante: Eliz")
    persona.inserir_nodo("Disciplina: Metodologia da Pesquisa Científico-Tecnológica - Prof.: Alessandra", "Estudante: Flávio")
    persona.inserir_nodo("Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini", "Estudante: Eliz")
    persona.inserir_nodo("Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini", "Estudante: Flávio")
    persona.inserir_nodo("Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini", "Estudante: Letícia")
    persona.inserir_nodo("Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini", "Estudante: Gabriel")
    persona.inserir_nodo("Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini", "Estudante: Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Estatística Descritiva - Prof.: Thays", "Estudante: Eliz")
    persona.inserir_nodo("Disciplina: Estatística Descritiva - Prof.: Thays", "Estudante: Flávio")
    persona.inserir_nodo("Disciplina: Estatística Descritiva - Prof.: Thays", "Estudante: Letícia")
    persona.inserir_nodo("Disciplina: Estatística Descritiva - Prof.: Thays", "Estudante: Gabriel")
    persona.inserir_nodo("Disciplina: Estatística Descritiva - Prof.: Thays", "Estudante: Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Álgebra Linear - Prof.: Renata Imada", "Estudante: Eliz")
    persona.inserir_nodo("Disciplina: Álgebra Linear - Prof.: Renata Imada", "Estudante: Flávio")
    persona.inserir_nodo("Disciplina: Álgebra Linear - Prof.: Renata Imada", "Estudante: Letícia")
    persona.inserir_nodo("Disciplina: Álgebra Linear - Prof.: Renata Imada", "Estudante: Gabriel")
    persona.inserir_nodo("Disciplina: Álgebra Linear - Prof.: Renata Imada", "Estudante: Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Projeto Integrador - Prof.: Rafael Christofano", "Estudante: Eliz")
    persona.inserir_nodo("Disciplina: Projeto Integrador - Prof.: Rafael Christofano", "Estudante: Flávio")
    persona.inserir_nodo("Disciplina: Projeto Integrador - Prof.: Rafael Christofano", "Estudante: Letícia")
    persona.inserir_nodo("Disciplina: Projeto Integrador - Prof.: Rafael Christofano", "Estudante: Gabriel")
    persona.inserir_nodo("Disciplina: Projeto Integrador - Prof.: Rafael Christofano", "Estudante: Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano", "Estudante: Eliz")
    persona.inserir_nodo("Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano", "Estudante: Flávio")
    persona.inserir_nodo("Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano", "Estudante: Letícia")
    persona.inserir_nodo("Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano", "Estudante: Gabriel")
    persona.inserir_nodo("Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano", "Estudante: Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline", "Estudante: Eliz")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline", "Estudante: Flávio")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline", "Estudante: Letícia")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline", "Estudante: Gabriel")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline", "Estudante: Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Inglês II - Prof.: Renata Belchior", "Estudante: Eliz")
    persona.inserir_nodo("Disciplina: Inglês II - Prof.: Renata Belchior", "Estudante: Flávio")
    persona.inserir_nodo("Disciplina: Inglês II - Prof.: Renata Belchior", "Estudante: Letícia")
    persona.inserir_nodo("Disciplina: Inglês II - Prof.: Renata Belchior", "Estudante: Gabriel")
    persona.inserir_nodo("Disciplina: Inglês II - Prof.: Renata Belchior", "Estudante: Luiz Gabriel")
    persona.imprimir()

    encontrado = persona.localizar_nodo("Estudante: Flávio")
    print("\nEncontrado - {}".format(encontrado))

main()