from arvore_t2 import Arvore

def main():

    persona = Arvore("FATEC Adamantina")
    persona.raiz.inserir_filho("Ciência de Dados")
    persona.inserir_nodo("Ciência de Dados", "Primeiro Módulo")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Algoritmos e Introdução à Computação - Prof.: Eliane Vendramini")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Gestão Ágil de Projetos - Prof.: Eliane Vendramini")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Matemática Básica - Prof.: Renata Imada")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Princípios de Ciência de Dados - Prof.: Rafael Christofano")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Economia da Informação, Inovação e Negócios Disruptivos - Prof.: Luciana Marcondes")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Produção de Textos Acadêmicos-Científicos I - Prof.: William Pereira")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Inglês I - Prof.: Renata Belchior")
    persona.inserir_nodo("Primeiro Módulo", "Disciplina: Metodologia da Pesquisa Científico-Tecnológica - Prof.: Alessandra")
    persona.inserir_nodo("Ciência de Dados", "Segundo Módulo")
    persona.inserir_nodo("Segundo Módulo", "Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini")
    persona.inserir_nodo("Segundo Módulo", "Disciplina: Estatística Descritiva - Prof.: Thays")
    persona.inserir_nodo("Segundo Módulo", "Disciplina: Álgebra Linear - Prof.: Renata Imada")
    persona.inserir_nodo("Segundo Módulo", "Disciplina: Projeto Integrador - Prof.: Rafael Christofano")
    persona.inserir_nodo("Segundo Módulo", "Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano")
    persona.inserir_nodo("Segundo Módulo", "Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline")
    persona.inserir_nodo("Segundo Módulo", "Disciplina: Inglês II - Prof.: Renata Belchior")
    persona.inserir_nodo("Ciência de Dados", "Terceiro Módulo")
    persona.inserir_nodo("Ciência de Dados", "Quarto Módulo")
    persona.inserir_nodo("Ciência de Dados", "Quinto Módulo")
    persona.inserir_nodo("Ciência de Dados", "Sexto Módulo")
    persona.raiz.inserir_filho("Gestão Comercial")
    persona.inserir_nodo("Gestão Comercial", "Primeiro Módulo")
    persona.inserir_nodo("Gestão Comercial", "Segundo Módulo")
    persona.inserir_nodo("Gestão Comercial", "Terceiro Módulo")
    persona.inserir_nodo("Gestão Comercial", "Quarto Módulo")
    persona.inserir_nodo("Gestão Comercial", "Quinto Módulo")
    persona.inserir_nodo("Gestão Comercial", "Sexto Módulo")
    persona.inserir_nodo("Disciplina: Algoritmos e Introdução à Computação - Prof.: Eliane Vendramini", "Eliz")
    persona.inserir_nodo("Disciplina: Algoritmos e Introdução à Computação - Prof.: Eliane Vendramini", "Flavio")
    persona.inserir_nodo("Disciplina: Gestão Ágil de Projetos - Prof.: Eliane Vendramini", "Eliz")
    persona.inserir_nodo("Disciplina: Gestão Ágil de Projetos - Prof.: Eliane Vendramini", "Flavio")
    persona.inserir_nodo("Disciplina: Matemática Básica - Prof.: Renata Imada", "Eliz")
    persona.inserir_nodo("Disciplina: Matemática Básica - Prof.: Renata Imada", "Flavio")
    persona.inserir_nodo("Disciplina: Princípios de Ciência de Dados - Prof.: Rafael Christofano", "Eliz")
    persona.inserir_nodo("Disciplina: Princípios de Ciência de Dados - Prof.: Rafael Christofano", "Flavio")
    persona.inserir_nodo("Disciplina: Economia da Informação, Inovação e Negócios Disruptivos - Prof.: Luciana Marcondes", "Eliz")
    persona.inserir_nodo("Disciplina: Economia da Informação, Inovação e Negócios Disruptivos - Prof.: Luciana Marcondes", "Flavio")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos I - Prof.: William Pereira", "Eliz")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos I - Prof.: William Pereira", "Flavio")
    persona.inserir_nodo("Disciplina: Inglês I - Prof.: Renata Belchior", "Eliz")
    persona.inserir_nodo("Disciplina: Inglês I - Prof.: Renata Belchior", "Flavio")
    persona.inserir_nodo("Disciplina: Metodologia da Pesquisa Científico-Tecnológica - Prof.: Alessandra", "Eliz")
    persona.inserir_nodo("Disciplina: Metodologia da Pesquisa Científico-Tecnológica - Prof.: Alessandra", "Flavio")
    persona.inserir_nodo("Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini", "Eliz")
    persona.inserir_nodo("Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini", "Flavio")
    persona.inserir_nodo("Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini", "Leticia")
    persona.inserir_nodo("Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini", "Gabriel")
    persona.inserir_nodo("Disciplina: Estrutura de Dados - Prof.: Eliane Vendramini", "Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Estatística Descritiva - Prof.: Thays", "Eliz")
    persona.inserir_nodo("Disciplina: Estatística Descritiva - Prof.: Thays", "Flavio")
    persona.inserir_nodo("Disciplina: Estatística Descritiva - Prof.: Thays", "Leticia")
    persona.inserir_nodo("Disciplina: Estatística Descritiva - Prof.: Thays", "Gabriel")
    persona.inserir_nodo("Disciplina: Estatística Descritiva - Prof.: Thays", "Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Álgebra Linear - Prof.: Renata Imada", "Eliz")
    persona.inserir_nodo("Disciplina: Álgebra Linear - Prof.: Renata Imada", "Flavio")
    persona.inserir_nodo("Disciplina: Álgebra Linear - Prof.: Renata Imada", "Leticia")
    persona.inserir_nodo("Disciplina: Álgebra Linear - Prof.: Renata Imada", "Gabriel")
    persona.inserir_nodo("Disciplina: Álgebra Linear - Prof.: Renata Imada", "Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Projeto Integrador - Prof.: Rafael Christofano", "Eliz")
    persona.inserir_nodo("Disciplina: Projeto Integrador - Prof.: Rafael Christofano", "Flavio")
    persona.inserir_nodo("Disciplina: Projeto Integrador - Prof.: Rafael Christofano", "Leticia")
    persona.inserir_nodo("Disciplina: Projeto Integrador - Prof.: Rafael Christofano", "Gabriel")
    persona.inserir_nodo("Disciplina: Projeto Integrador - Prof.: Rafael Christofano", "Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano", "Eliz")
    persona.inserir_nodo("Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano", "Flavio")
    persona.inserir_nodo("Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano", "Leticia")
    persona.inserir_nodo("Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano", "Gabriel")
    persona.inserir_nodo("Disciplina: Ciência de Dados e Marketing Digital - Prof.: Rafael Christofano", "Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline", "Eliz")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline", "Flavio")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline", "Leticia")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline", "Gabriel")
    persona.inserir_nodo("Disciplina: Produção de Textos Acadêmicos-Científicos II - Prof.: Jaqueline", "Luiz Gabriel")
    persona.inserir_nodo("Disciplina: Inglês II - Prof.: Renata Belchior", "Eliz")
    persona.inserir_nodo("Disciplina: Inglês II - Prof.: Renata Belchior", "Flavio")
    persona.inserir_nodo("Disciplina: Inglês II - Prof.: Renata Belchior", "Leticia")
    persona.inserir_nodo("Disciplina: Inglês II - Prof.: Renata Belchior", "Gabriel")
    persona.inserir_nodo("Disciplina: Inglês II - Prof.: Renata Belchior", "Luiz Gabriel")
    persona.imprimir()

    encontrado = persona.buscar(input("\nDigite um nome para confirmar se está na estrutura: "))
    print("\nEncontrado - {}".format(encontrado))

main()